server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: uaa
  main:
    allow-bean-definition-overriding: true

dubbo:
  consumer:
    check: false
  registry:
    address: nacos://127.0.0.1:8848
  cloud:
    subscribed-services: user-service
  protocol:
    port: -1
    name: dubbo
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  global-config:
    id-type: 0
    capital-mode: true
    db-column-underline: true
    field-strategy: 1
    logic-delete-value: 1
    logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.lordy.uaa.entity
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  pageSizeZero: true
  params:
    count:
      countSql
